### ISSUE TITLE
Problem With CKSurf SQL

### ISSUE THREAD

**Issue by NekoMajo** [nikooo777/ckSurf#17]
Hello! First of all I love the plugin, an Im thankful for all the work you put in. I do have a approbelm though. Wehenver anyone finishes the map They get this error: Failed to save correctly contact an admin. and the rank shows 99999/1. After the server is reset, none of the times are saved either. I apprectiate the help!

**Comment by Furchee** [comment]
Your SM version is too new. I used v1.9.0.5996
Sadly as of right now the one I have been using has broke since the latest CSGO update. We can't do much anymore until someone updates something. (If they will at all.)
I'll test other branches in hopes of getting one to work with the new update, but I think it's officially broken again.

**Comment by nikooo777** [comment]
works fine with the latest sm 1.8 release

**Comment by Furchee** [comment]
Wasn't able to test until I got home from work, but yes it does indeed.

**Comment by nikooo777** [comment]
to make sure everyone knows, i just checked again and Sourcemod 1.9 **breaks** compatibility with cksurf. Don't use sm 1.9

closing this issue
