### ISSUE TITLE
Chat Processor

### ISSUE THREAD

**Issue by ajackson420** [nikooo777/ckSurf#4]
*Note - There is not a standing issue with the plugin itself, this is a bug when running alongside another common plugin. I'm posting it here as more of an adjustment request for a future update. 

When using ckSurf with Zeph's Store (and other chat & name tag modifying plugins) and having ckSurf's chat processing enabled (ck_chat_enable "1"), you cannot do any name tag or name/chat color modifying (i.e- buying name and chat colors/tags from the !store). However, when you disable ckSurf's chat processing (ck_chat_enable "0"), all of those name/chat colors and tags work through the store. The downside is that commonly used ckSurf chat commands like !r, !s, !b, etc...all show up in chat instead of being filtered out, since chat processing is disabled all together.

If it's simple enough, in a future update maybe you could adjust ckSurf's chat processing to allow for other plugins to modify name and message properties while still filtering out chat commands like normal.  Thank you for your work on maintaining and updating this plugin.

**Comment by nikooo777** [comment]
Hi,
Thanks for reporting the issue,
Unfortunately this is not very easy to handle, the reason is that both plugins hook the say event and override eachother.

Perhaps a way to handle this would be to edit zeph's store and delay they hooks (perhaps using post?).

As for the solution of disabling ck_chat_enable, i think you could solve that by having a chat filter or by hiding these commands, i'm pretty sure there is a plugin for that or even sourcemod natively.
