### ISSUE TITLE
Disabling run SR comparison in hint HUD?

### ISSUE THREAD

**Issue by M-archand** [nikooo777/ckSurf#63]
This is in regards to the bug some of us seem to be having that happens when you pass a checkpoint or reach a stage, your run time compared to the Server Record is shown in the timer hint box and causes your speed to disappear. Seen here: 
![30507504-084e27a2-9a5c-11e7-9be3-2eb8d7569083](https://user-images.githubusercontent.com/13469995/31915911-b6a16be2-b826-11e7-8ee0-39844d3622ef.png)
This has also been talked about in more detail in issue #50 

I'm wondering if anyone knows how to disable this feature completely as a temporary fix, having it show up just in chat is fine with me. Or if anyone just knows where in the code this function is done, I already tried looking through the sp code and couldn't find anything too obvious on my own. Any help would be much appreciated :D

**Comment by fluffyst** [comment]
Center hud code starts here https://github.com/nikooo777/ckSurf/blob/master/csgo/addons/sourcemod/scripting/ckSurf/misc.sp#L2804 and SR comparison is https://github.com/nikooo777/ckSurf/blob/c0eaa6c031777edc58ca0bbc113095d97a5c5858/csgo/addons/sourcemod/scripting/ckSurf/misc.sp#L2963

I believe the issue happens because with all the added colours to the prefixs (rank, stage, speed etc) there's too many characters since they're actually HTML `<font color='#xyxyxy'>` if that makes sense, so you could fix it by removing the colours most likely.

**Comment by the133448** [comment]
my latest fork  fixes this, waiting for maximums to pull it so it can be added to this repository.

**Comment by 2called-chaos** [comment]
@the133448 what did you change? no offense but your commit messages are useless :D

**Comment by the133448** [comment]
:( 
Changes are:
* Adjusting Records if it is achieved on another server on same db, at same time. So someone on server x gets kitsune record whilst server b is playing kitsune. So server b now gets the record set on server a instantly.
* Fixed blocked command list so that if a command has args, it will still hide it.
* added tier 7 
* added admin reminder to add tiers
* Added cross server announcments when a map record is broken
* added hud messages when a map record is broken
* added in custom sound shop, so that players can select what others hear when they break server/bonus/personal records
* added colour gradient to speed panel
* fixed issues with formattig on center panel
* Added in customizable adverts to center panel
* added pause exploit fix

**Comment by 2called-chaos** [comment]
Hmm I may borrow "Fixed blocked command list so that if a command has args, it will still hide it." for #65 :D

Just as a recommendation: If you commit more often (opposed to version batches) it's easier to find specific changes, "git blame" works way better and merging with conflicts becomes way easier :)
