### ISSUE TITLE
Issues with latest version

### ISSUE THREAD

**Issue by jljr222** [nikooo777/ckSurf#7]
Hi,

Having some issues with the latest version of ckSurf niko. On my server I have VIPs set to "o" and it seems everyone is getting VIP access for the most part. I've also had some people lose their ranks entirely. I've also seen some people who live in the US (like Texas) be given a location of CA. Just a few issues I've noticed.

Any assistance would be great!

**Comment by blackhawk74** [comment]
Update your Sourcemod to the latest 1.8 build (5947) or 1.9 build (5996 - untested). Fixes a get client auth issue which could be causing your issue. If the issue is solved or persists give an update! :)

**Comment by nikooo777** [comment]
Hey!Are you on the latest sm1.8 build?Sounds to me like this is the issueSent from my Huawei Mobile-------- Original Message --------Subject: [nikooo777/ckSurf] Issues with latest version (#7)From: John Lewis To: nikooo777/ckSurf CC: Hi,

Having some issues with the latest version of ckSurf niko. On my server I have VIPs set to "o" and it seems everyone is getting VIP access for the most part. I've also had some people lose their ranks entirely. I've also seen some people who live in the US (like Texas) be given a location of CA. Just a few issues I've noticed.

Any assistance would be great!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nikooo777/ckSurf","title":"nikooo777/ckSurf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nikooo777/ckSurf"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Issues with latest version (#7)"}],"action":{"name":"View Issue","url":"https://github.com/nikooo777/ckSurf/issues/7"}}}

**Comment by jljr222** [comment]
I noticed this last night, I was WAY behind in my SM build. It looks to be all good now. Thanks guys!
