### ISSUE TITLE
New record no points

### ISSUE THREAD

**Issue by Destinyg133** [nikooo777/ckSurf#9]
Hello niko, today i finally got your version of cksurf, first of all nice job, 

I've got a big problem, i did 2 records, both of time i didnt get points
thats a bug from original author, and now its in your version too,
any way of fixing?

edit2: also, its not only for records, sometimes players dont even recieve points for passing

edit3: plus whats up with some colours not shown? some are white, and some are with colours

**Comment by nikooo777** [comment]
Hi, have you figured out yet? You probably didn't install the plugin in a clean way, or you forgot to port over the changes required from 1.18 to 1.19 (listed in the readme).
make sure to read the error log too

**Comment by Destinyg133** [comment]
yea, the problem was i didnt put some maps in mappool, but also sometimes, its rare but it does happend it doesnt give points, will test it more out

**Comment by Destinyg133** [comment]
Destiny <csadria.org> finished the map with a time of (01:08:24). [rank #1/1 | record 01:08:24]
[CK] Destiny <csadria.org> scored a new MAP RECORD
-----
Before calculation:
g_pr_multiplier: 156
g_pr_points: 0
------
-----
after calculation:
g_hExtraPoints: 15
g_pr_points: 2340

altho it was in mappool, didnt get new record points for some reason

**Comment by Destinyg133** [comment]
still not sure if print msg sometimes doesnt work, but i think you get points every time
will put on close

**Comment by mloveless1227** [comment]
This issue should be opened back up because not receiving points is a definite problem within this plugin still as it has been since day one. Happens quite frequently in my experience. Plugin has no errors or anything, all map cycle files are setup appropriately, and it still happens regularly where players get no  points. It happens both on brand new maps with no times at all and maps that have lots of existing times.  Can't seem to replicate the times where it happens though.
